# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-IMAPQueue
version:      0.01
version_from: lib/Mail/IMAPQueue.pm
installdirs:  site
requires:
    List::Util:                    0
    Mail::IMAPClient:              0
    Scalar::Util :                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
